#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-flake8_blind_except
Version  : 0.2.1
Release  : 29
URL      : https://files.pythonhosted.org/packages/be/f8/cb5e0b8c948cb347b8942cb7ce73292a77ec8f9eafb8d5db999c5c1ac62f/flake8-blind-except-0.2.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/be/f8/cb5e0b8c948cb347b8942cb7ce73292a77ec8f9eafb8d5db999c5c1ac62f/flake8-blind-except-0.2.1.tar.gz
Summary  : A flake8 extension that checks for blind except: statements
Group    : Development/Tools
License  : MIT
Requires: pypi-flake8_blind_except-python = %{version}-%{release}
Requires: pypi-flake8_blind_except-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
flake8-blind-except
===================
A flake8 extension that checks for blind, catch-all ``except:`` and ``except Exception:`` statements.

%package python
Summary: python components for the pypi-flake8_blind_except package.
Group: Default
Requires: pypi-flake8_blind_except-python3 = %{version}-%{release}

%description python
python components for the pypi-flake8_blind_except package.


%package python3
Summary: python3 components for the pypi-flake8_blind_except package.
Group: Default
Requires: python3-core
Provides: pypi(flake8_blind_except)

%description python3
python3 components for the pypi-flake8_blind_except package.


%prep
%setup -q -n flake8-blind-except-0.2.1
cd %{_builddir}/flake8-blind-except-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647643646
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
